### ISSUE TITLE
Crear el archivo index.html enlazado a un archivo CICLOS.js

### ISSUE THREAD

**Issue by andreswinck** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#1]
Hola Dante se te asigno la tarea de JS de esta semana

**Comment by mzadante** [comment]
Ok Buen dia, gracias por tomarte la tarea de  piloto jejeje ahora lo miro.

**Comment by mzadante** [comment]
Bueno creado la carpeta del proyecto y el codigo html contenedor falta que le agregen en su interior los codigos javascript y lo testeen en su funcionamiento. sin mas me despido

**Comment by andreswinck** [comment]
terminado
