### ISSUE TITLE
Dante tarea asignada

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#14]
Tarea asignada ..  Crar un arraglo utilizando  ciclos del proyecto anterior

**Comment by mzadante** [comment]
Dale dario querido nos ponemos las pilas inmediatamente

**Comment by mzadante** [comment]
cree una funcion en javaScript la cual se llama agregarElementos(), la cual crea un prompt preguntandole al usuario cuantos elementos quiere agregar, y crea un arreglo vacio, luego itera con un ciclo for la cantidad de veces que decidio el usuario que itere y despues le pide al usuario que agregue los elementos deseados, y este ciclo for agrega los elementos al arreglo vacio con push y al finalizar muestra el resultado en con un mensaje de alert de los elementos añadidos.

**Comment by mzadante** [comment]
Bueno jefe de equipo, ya agregue mi codigo cualquier cosa, avisame abrazo lider team.
