### ISSUE TITLE
Abel aqui te dejo la terea de la semana

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#16]
Tarea asignada ..  Crar un arraglo utilizando  ciclos del proyecto anterior

**Comment by Abelino537** [comment]
Genial gracias Dario

**Comment by Abelino537** [comment]
Ya estoy trabajando en el proyecto

**Comment by Abelino537** [comment]
Trabajo terminado
