### ISSUE TITLE
Franco aqui queda tu tarea para la semana

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#18]
Tarea asignada ..  Crar un arraglo utilizando  ciclos del proyecto anterior

**Comment by dwc1970** [comment]
Franco pone tu nombre `para que te podamos ubicar para asignar la tarea por que ese de chorifan no lo sabia .. besis

**Comment by Chorifrann** [comment]
Ah disculpa, tenia la cuenta creada de antes de la tecnicatura y nunca lo cambie

**Comment by Chorifrann** [comment]
Termine el  trabajo asignado.
