### ISSUE TITLE
1.3 Funciones tipo Expresión

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#23]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by Abelino537** [comment]
comienzo a trabajar en mi parte

**Comment by Abelino537** [comment]
TRabajando y viendo los videos

**Comment by Abelino537** [comment]
ya subi el archivo con el codigo de una funcion de tipo expresion, ademas agrege info en el readme  sobre el tema

**Comment by mzadante** [comment]
Gracias Abel, ahora lo miro abrazo

**Comment by mzadante** [comment]
Abel querido impecable lo suyo, estate atento por si mañana no completan las tareas los demas, vamos a tener que finalizarlo nosotros abrazo
