### ISSUE TITLE
1.4 Funciones de Tipo self y invoking

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#24]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by andreswinck** [comment]
En proceso

**Comment by mzadante** [comment]
Gracias Andres

**Comment by mzadante** [comment]
Ya vi tu trabajo, ladron de scripts, pusiste el tuyo usando el mio, ja y el tuyo quedo bien pero me estropeaste el mio, en fin ya esta solucionado y listo, estate atento para el cierre de este scrum mañana, por si me tenes que ayudar a finalizarlo
