### ISSUE TITLE
1.5 Tipos de datos en una función

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#25]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by dwc1970** [comment]
Se sube el código en Js de funciones y en el Readme se da una breve explicación de tipos de datos en una función Js

**Comment by dwc1970** [comment]
Se mueve la tarjeta de spring backlog a Terminado

**Comment by mzadante** [comment]
Hola dario vi tu ejercicio y haria falta respetar la consigna del proyecto, asique despues te explico en vivo y te doy una mano por si no entendes abrazo

**Comment by dwc1970** [comment]
Hola Dante, ahi me voy a poner a corregirlo, si se me complica te mando un Whattssap para que me des una mano.

**Comment by dwc1970** [comment]
ya cargue el codigo , falta solucionar la salida..
