### ISSUE TITLE
1.7 Argumentos y parámetros

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#27]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by mzadante** [comment]
Hola jere ahora lo miro y te aviso si esta bien

**Comment by mzadante** [comment]
Hola Jere, me equivoque crei que habias puesto tu ejercicio y cuando me fije en el codigo vi que todavia no esta, recorda que mañana cierro el proyecto a ponerle pilas lee bien las consignas del readme, abrazo

**Comment by JereRiquero** [comment]
Dante hay termine de subir todo, disculpa la tardanza

**Comment by mzadante** [comment]
Dale gracias enseguida lo miro

**Comment by mzadante** [comment]
Hola Jeremias si mejoro bastante ya lo veo en el html pero no funciona lo que dice que hace, y vi que lo agregastes al readme la teoria bien, salvo ese detalle de que no funca, pero bien si podes miralo.

**Comment by JereRiquero** [comment]
Ahora lo miro Dante
