### ISSUE TITLE
1.8 Concepto hoisting

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#28]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by mzadante** [comment]
Hola franco, si necesitas ayuda avisanos y te ayudamos, a meterle pila que mañana cierro el proyecto abrazo

**Comment by Chorifrann** [comment]
Estoy en los ultimos pasitos de tener el codigo listo :D

**Comment by Chorifrann** [comment]
Termina2

**Comment by mzadante** [comment]
Joya franco más tarde lo miro
