### ISSUE TITLE
1.9 Paso por valor Y  1.9.1 Paso por referencia

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#29]
En este escrum cada integrante del grupo no-code agregara en JavaScript el uso de funciones de la clase de la semana del 17-03-2023 y este mismo cerrara el 01-03-2023.

Tendrian que colocarlos dentro del mismo html ya creado en el proyecto, asi tendremos un unico html que muestra todo lo que vimos en la tercera clase de javascript en Laboratorio III.
Y luego en el readme cada uno deberá colocar una breve descripción del tema asignado.

Extras: si quieren mejorarlo visualmente son libres de hacerlo, todo lo que se les ocurra es bienvenido!

**Comment by mzadante** [comment]
Gracias eze, ahora lo miro y si esta ok te aviso

**Comment by mzadante** [comment]
Hola Ezequiel, fijate si podras integrar lo que vos hiciste en el html index que esta creado alli para que sea mas visual y te falto rellenar en el readme la teoria de paso por valor y referencia gracias querido y recorda que mañana cierro el proyecto, estate atento por si los demas no lo completan lo vamos a tener que completar nosotros

**Comment by ezequielmariscal** [comment]
dale dante
.. emm no han creado ningun index
ahi agregue el readme

**Comment by ezequielmariscal** [comment]
aah ahi actualize y la estoy viendo q le han metido
