### ISSUE TITLE
Importante (Leer)

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#30]
Vamos a realizar un HTML(Utilizando input) general para todos los trabajos ya que estamos trabajando con objetos, la participación va a ser en grupos de a dos personas. Va a constar de 4 formularios:
1_Formulario de registro medico(Andres y Ezequiel): Utilizando (new Obejct)
2_Formulario para reclutador de empresas(Dante y Dario): Utilizando (For in)
3_Formulario de inscripción escolar(Lucas y Franco): Al final del formulario dar la opción de modificar un atributo
4_Formulario patentacion de un vehículo(Abel y Jeremías): Al final del formulario dar la opción de agregar o eliminar un atributo
Siempre es bienvenido darle una buena imagen con CSS, eso queda a colaboración de cada uno
A la hora de subir los trabajos en el HTML, respetar el orden que les acabo de asignar

**Comment by andreswinck** [comment]
Bien, estaria bueno que crearas el HTML general para agregar ahi el formulario que nos toca, ademas de crear la carpeta del proyecto de esta semana donde guardar los archivos

**Comment by JereRiquero** [comment]
Si Andrés, hoy el Dante me ayuda con eso

**Comment by mzadante** [comment]
joya querido arrancando

**Comment by JereRiquero** [comment]
Proyecto realizado:
El proyecto de esta se semana se dividió en 4 equipos de 2 personas, con la finalidad de realizar 4 formularios, cada uno realizado con un método diferente, mostrando los conocimientos aprendidos durante la clase 4.
1_Registro medico
2_Formulario para reclutador de empresas
3_Formulario para inscripción escolar
4_Formulario para patentación de vehículos

Muy buen trabajo chicos, queda terminado el proyecto de la semana 4, fue un gusto ser el Scrum Master y espero que sigamos trabajando así de bien.
