### ISSUE TITLE
Formulario para reclutador de empresas (Dante y Dario)

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#31]
Realizar un formulario utilizando input con los siguientes atributos base:

Nombre completo
Edad
DNI
Estudios
Areas de trabajo
Generar los metodos y conexiones correspondientes con un botón que muestre los datos ingresados en un alert
Son libres de agregar mas atributos según lo sientan necesario
Utilizar (For In), nombre del objeto (persona2)

**Comment by mzadante** [comment]
dale querido ahora me pongo en contacto con el dario y nos mponemos mano a la obra

**Comment by mzadante** [comment]
Ya cree el Html de mi formulario le agregue estudios y area de trabajo

**Comment by mzadante** [comment]
Listo Jere mi parte del codigo esta finalizado, ya termine mi scrum, solo falta que Dario pongo el fin de una funcion que creamos en javaScript y mueva luego la tarjeta a finalizado, nos vemos querido

**Comment by dwc1970** [comment]
Listo a tarea ya esta terminada
