### ISSUE TITLE
Formulario para patentamiento de vehículos (Abel y Jeremías)

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#32]
Realizar un formulario utilizando input con los siguientes atributos base:

Nombre completo
Edad
DNI
Patente
Modelo
Marca
Generar los métodos y conexiones correspondientes con un botón que muestre los datos ingresados en un alert
Son libres de agregar mas atributos según lo sientan necesario
** creación del objeto (persona4), recuerden que al final del formulario dar la opción de agregar o eliminar un atributo en un prompt **

**Comment by Abelino537** [comment]
comenzamos a trabajar en el proyectp

**Comment by Abelino537** [comment]
codigo terminado
