### ISSUE TITLE
Formulario para registro medico (Andres y Ezequiel)

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#33]
Realizar un formulario utilizando input con los siguientes atributos base:

Nombre completo
Edad
DNI
Enfermedad o condición
Grupo sanguíneo
Generar los metodos y conexiones correspondientes con un botón que muestre los datos ingresados en un alert
Son libres de agregar mas atributos según lo sientan necesario
Utilizar (new Object) para la creacion del objeto (persona1)

**Comment by andreswinck** [comment]
recibido y en proceso

**Comment by andreswinck** [comment]
terminado
