### ISSUE TITLE
Formulario para inscripción escolar (Lucas y Franco)

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#34]
Realizar un formulario utilizando input con los siguientes atributos base:

Nombre completo
Edad
DNI
Escuela
Generar los métodos y conexiones correspondientes con un botón que muestre los datos ingresados en un alert
Son libres de agregar mas atributos según lo sientan necesario
**Creación del objeto (persona3), recuerden que al final del formulario dar la opción de modificar un atributo en un prompt **

**Comment by LucasSalinas** [comment]
Terminamos el codigo con Franco
