### ISSUE TITLE
Información de las tareas  de este semana

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#35]
Buenas noches chicos, disculpen mi demora con la subida de actividades me enferme y e estado medio indispuesto.

A continuación les dejare las tareas en base a los videos vistos en clase, ustedes vayan viendo lo que les e asignado y en estos días voy a crear un proyecto para unificar todos los conocimientos en un html para la entrega. cualquier duda o consulta no duden en preguntarme.

**Comment by mzadante** [comment]
ya tengo lo mio en increment esperando tu proximo issue

**Comment by andreswinck** [comment]
Hola, el mio también está terminado esperando tu issue

**Comment by Abelino537** [comment]
Buenas noches chicos, ahí revise todos los codigos e hice correcciones, como aun quedan muchas cosas por cambiar voy a finalizar el proyecto el dia martes

**Comment by Abelino537** [comment]
Se finaliza el proyecto de esta semana con su respectivo index mostrando el codigo de cada uno de los integrantes.
