### ISSUE TITLE
Dante: 5.2  Constructores de objetos

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#38]
Ver el video 5.2 de la clase 5 y desarrollar un código simple aplicando lo enseñado.

**Comment by mzadante** [comment]
Hola querido, dale me pongo en eso, lo ponemos simple, lo dejo en una carpeta que se llamara  ejercicio 5-2 de objetos

**Comment by mzadante** [comment]
Listo abel miralo y decime si es eso lo que necesitabas?

**Comment by Abelino537** [comment]
Hola Dante, esta bien el codigo pero es de get y set y yo te habia asignado el punto 5.2 sobre la creación de contructores para los objetos

**Comment by mzadante** [comment]
okas dale ya lo cambio

**Comment by mzadante** [comment]
Listo Abel ya quedo listo el metodo constructor de la clase 5.2 de Objetos de JavaScript y agregue la teoria en el Readme, abrazo
