### ISSUE TITLE
Lucas: 5.3 Agregar métodos al constructor del objeto

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#39]
Ver el video 5.3 de la clase 5 y desarrollar un código simple aplicando lo enseñado.

**Comment by Abelino537** [comment]
Buenas Lucas revise tu codigo y esta mal, has hecho el tema del punto 5.2 contructor de objetos y a vos te toco el punto 5.3 que es agregar un metodo dentro del contructor. lee los titulos por favor

**Comment by LucasSalinas** [comment]
Buenas, solucionado
