### ISSUE TITLE
Añadir un ejercicio usando ciclo WHILE en JS

### ISSUE THREAD

**Issue by andreswinck** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#4]

**Comment by Abelino537** [comment]
Haciendo el ejercicio del ciclo while "Determinar si el año es bisiesto"

**Comment by Abelino537** [comment]
Ejercicio con el ciclo while en JS terminado, subido en la solapa de JS con su respectivo commit
