### ISSUE TITLE
Dario: 5.4 Distintas formas de crear objetos

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#40]
Ver el video 5.4 de la clase 5 y desarrollar un código simple aplicando lo enseñado. Solo hacer las siguientes formas:

- Caso objetos 1 y 2
- Caso String 1 y 2
- Caso números 1 y 2

**Comment by dwc1970** [comment]
Ya cargue la tarea que tenia asignada

**Comment by Abelino537** [comment]
hola Dario ahi revise tu condigo, esta bien hecho
