### ISSUE TITLE
Ezequiel: 5.4 Distintas formas de crear objetos

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#41]
Ver el video 5.4 de la clase 5 y desarrollar un código simple aplicando lo enseñado. Solo hacer las siguientes formas:

- Caso Boolean 1 y 2
- Caso Arreglo 1 y 2
- Caso Funciones 1 y 2

**Comment by ezequielmariscal** [comment]
En proceso...

**Comment by ezequielmariscal** [comment]
terminado...

**Comment by Abelino537** [comment]
ya revise tu codigo eze esta joya bien hecho
