### ISSUE TITLE
Crea una clase llamada los simpson, con nombre, apellido y su constructor

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#46]
Dante eres el 2do . cada uno va a realizar lo que se le pide en un mismo js. para que todos avancemos es importante que empieces tu... crea tu el js y de ahi van agregando todos su partecita

**Comment by mzadante** [comment]
hola Eze dale gracias ya mismo me pongo hacer el script abrazo

**Comment by mzadante** [comment]
ya cree la clase losSimpsons con su constructor y agregue teoria al readme sobre el constructor que es y para que funciona, cualquier cosa me avisan

**Comment by mzadante** [comment]
terminada mi parte
