### ISSUE TITLE
Agrega getter y setter a clase los simpson

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#47]
Andres sos el nro 2 de la lista..vas despues del dante . Cuandop agregue el dante lo suyo ahi agregas los setter and getter , todo en un mismo archivo js

**Comment by andreswinck** [comment]
ok, ahora lo hablo con Dante

**Comment by andreswinck** [comment]
agregados lo getters y setters
