### ISSUE TITLE
Añadir un ejercicio usando ciclo DO while en JS

### ISSUE THREAD

**Issue by andreswinck** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#5]
Asignada la tarea semanal de JS

**Comment by Chorifrann** [comment]
Terminado el ejercicio usando ciclos DO While en JS

**Comment by Chorifrann** [comment]
Ya subi el archivo gente. Esta en la carpeta "Ciclo Do While Franco"
