### ISSUE TITLE
BolaDeNieve9 acaba de morir, Añade BolaDeNieve10 reemplazando a BolaDeNieve9

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#52]
Dario vas ultimo... Fijate si creando una nueva mascota se reeemplaza la anterior, sino borrala directamente. Va todo en un mismo js.

**Comment by dwc1970** [comment]
OK, AHI VEO LA TAREA PARA CARGAR

**Comment by dwc1970** [comment]
Tarea cargada
