### ISSUE TITLE
Crear una conexion a la base de datos utilizando Pycharm

### ISSUE THREAD

**Issue by andreswinck** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#54]
En el proyecto agregado en el repo hay una conexion simple a la base de datos postgreSQL, tu trabajo consiste en mejorar la conexion a la base de datos, agregando exepciones y demas cosas necesarias vistas en clase

**Comment by andreswinck** [comment]
Se optimiza la conexión a postgreSQL con with.

**Comment by mzadante** [comment]
gracias andres dejo tu tarjeta aqui hasta que armames todo el juego para la release
