### ISSUE TITLE
Crear una consulta a la base de datos para traer las preguntas al juego

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#58]
En el codigo del repo esta la version 1.0 del proyecto cargado con una consulta muy simple a la base de datos, tu trabajo es mejorar esa consulta a la base de datos para ya sea traer todas las preguntas o traerlas de a una, muchas suerte abel estamos en contacto

**Comment by Abelino537** [comment]
comienzo a trabajar en mi parte del código, ya importe la base de datos cargada del proyecto 1.0

**Comment by Abelino537** [comment]
como mi parte del código la hizo otro compañero por error comienzo a trabajar en una nueva adicion para el juego de trivia que consta en armar una tabla en la bd que guarde el puntaje de los jugadores, tratando de imitar a los juegos de las maquinas arcade

**Comment by Abelino537** [comment]
finalizo mi tarjeta
