### ISSUE TITLE
Crear un metodo para obtener el Nombre del jugador para mostrarlo al final con la puntuacion del juego

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#59]
En el codigo cargado al repo hay que crear un metodo que pida el nombre del jugador y que este nombre tiene que salir al finalizar el juego mostrando la puntuacion obtenida por este mismo, tendras que ponerte en contacto con los demas compañeros especialmente con el encargado de la funcion de mostrar puntaje del jugador, suerte lucas

**Comment by LucasSalinas** [comment]
Creado el metoddo para el nombre del jugador y mostrado al final del juego, junto con la puntuacion

**Comment by LucasSalinas** [comment]
Terminada la tarea
