### ISSUE TITLE
Crear algun metodo para almacenar las preguntas obtenidas de la base de datos

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#60]
En el repo hay un metodo simple de almacenamiento de las preguntas obtenidas de la base de datos, tendrias que mejorarlo o separarlo de la clase principal, o darle la utilidad mas a decuada posible, suerte Jere y estamos en contacto

**Comment by JereRiquero** [comment]
Comienzo a trabajar en el proyecto

**Comment by JereRiquero** [comment]
Dante hay optimicé mi parte del código, fíjate si esta bien

**Comment by mzadante** [comment]
dale jere en breves lo reviso

**Comment by mzadante** [comment]
Jere que hiciste en el codigo mandame una captura o marcalo con comentarios porfa

**Comment by mzadante** [comment]
Listo revisado lo paso para finalizado para luego juntar todo y hacer la release cierro el caso
