### ISSUE TITLE
Crear una funcion para que las preguntas sean aleatorias

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#61]
Hola eze en el repo del codigo basico que ya pasamos previamente en version simple, hay una funcion que trata las preguntas del juego en forma aleatoria, bueno trata de perfeccionarla porque creo que alguna falla tenia, tambien tenes que ponerte de acuerdo con los chicos que obtienen las preguntas de la base de datos, porque hasta ahora las traemos todas juntas y el juego las mezcla, suerte eze

**Comment by ezequielmariscal** [comment]
Se agrega la funcion aleatoria para las pregunta trivia python, Quedando listo para revision
