### ISSUE TITLE
Crear un metodo para preguntar al jugador, determinar si es correcta, asignar puntaje, mostrar puntaje final con nombre del jugador

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#62]
Hola Franco, bueno practicamente tenes que crear el super metodo, el cual interactua con el jugador, debera este metodo determinar como responde el jugador y mostrar el nombre del jugador y puntaje final ponete en contacto con los otros compañeros porque  tenes muchas acciones compartidas, especialmente con el Dario que es el encargado de estilizar la app, suerte Franco

**Comment by Chorifrann** [comment]
Finalizado
