### ISSUE TITLE
Reunir el codigo y verificar el correcto funcionamiento de la app

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#64]

**Comment by mzadante** [comment]
Bueno, como lider de scrum me designo y designo algun compañero para que al finalizar los Spring juntemos las partes del codigo y realicemos los test correspondientes para que funcione como corresponda el juego de Trivia, este mismo lo trataremos de cerrar si el release funciona correctamente

**Comment by andreswinck** [comment]
Se reune y se prueba el juego, el cual funciona correctamente.

**Comment by Abelino537** [comment]
Revisamos el codigo de la trivia con las partes de cada uno de los integrantes del grupo y ajustamos los archivos en un rar subido a git hub

**Comment by mzadante** [comment]
Bien bueno cierro el scrum cuando hagamos el release

**Comment by mzadante** [comment]
Fin Proyecto
