### ISSUE TITLE
Tarea 1: Crear clase padre.

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/TERCER-SEMESTRES-GRUPO-NO-CODE#65]
1- DANTE y EZEQUIEL:
- Crear la clase padre “Mueble” junto con su método constructor.
- Sus parámetros serán “material” y “color”.
- Agregar getters y setters de la clase padre.

Aviso en general: Recuerden comentar el código haciendo alusión a los temas de la clase y también rellenen el README según el tema que trabajaron.

**Comment by LucasSalinas** [comment]
Hola chicos, estuve revisando, no pusieron el nombre de la clase que indique, al igual que el nombre de los parametros. 
Tambien muevan el archivo .js a la carpeta de la clase 7 que habia creado.

**Comment by mzadante** [comment]
Hola lucas recien miro tu mensaje te falta crea una milestone para el proyecto y labels, revisa eso y si no entendes hacemos conferencia en discord, yo no e creado nada hasta ahora, y por lo que decis a lo mejor lo realizo el Ezequiel
